added spring security
vladshender/Online-Book-Store pull request #11
Opened 2024-08-08 10:29 UTC by vladshender

2024-08-09 08:16 UTC, Elena-Bruyako requested changes
Good job! See comments

2024-08-09 08:16 UTC, Elena-Bruyako commented on src/main/java/com/example/controller/BookController.java
> +    @PreAuthorize("hasAuthority('ADMIN')")
Завжди додавай ROLE_ при використанні методу hasAuthority(), наприклад, hasAuthority("ROLE_CUSTOMER").

See the lecture material

2024-08-09 08:16 UTC, Elena-Bruyako commented on src/main/java/com/example/model/User.java
> +    @ManyToMany(fetch = FetchType.EAGER)
```suggestion
    @ManyToMany
```

2024-08-09 08:16 UTC, Elena-Bruyako commented on src/main/java/com/example/model/User.java
> +        return roles.stream()
```suggestion
        return roles;
```

2024-08-09 08:16 UTC, Elena-Bruyako commented on src/main/java/com/example/security/CustomUserDetailsService.java
> +                        () -> new EntityNotFoundException("Can`t find user bu email: " + email)
```suggestion
                        () -> new EntityNotFoundException("Can`t find user by email: " + email)
```

2024-08-09 08:16 UTC, Elena-Bruyako commented on src/main/java/com/example/service/user/UserServiceImpl.java
> +        user.setPassword(passwordEncoder.encode(user.getPassword()));
Should we set User role?

2024-08-09 11:05 UTC, vladshender commented
without FetchType.Eager, a LazyInitializationException is thrown

2024-08-10 13:14 UTC, sarakhmen approved these changes

2024-08-14 17:08 UTC, merged