added BookController and Mapper
vladshender/Online-Book-Store pull request #5
Opened 2024-06-23 12:07 UTC by vladshender

2024-06-23 14:48 UTC, sarakhmen requested changes
let's improve your solution :)

2024-06-23 14:48 UTC, sarakhmen commented on src/main/java/com/example/service/BookServiceImpl.java
> +                .toList();
is it possible to map list of bookdtos directly using mapper? I mean you shouldn't use stream here and map each dto separately

2024-06-24 07:54 UTC, Elena-Bruyako requested changes
Good job! let's improve your solution!

2024-06-24 07:54 UTC, Elena-Bruyako commented on pom.xml
> +			<version>3.3.1</version>
```suggestion
```

2024-06-24 07:54 UTC, Elena-Bruyako commented on pom.xml
> +			<version>1.5.5.Final</version>
Add <mapstruct.version> to properties 
```suggestion
			<version>${mapstruct.version}</version>
```

2024-06-24 07:54 UTC, Elena-Bruyako commented on pom.xml
> +							<version>1.18.24</version>
```suggestion
							<version>${lombok.version}</version>
```

2024-06-24 07:54 UTC, Elena-Bruyako commented on pom.xml
> +					<source>17</source>
Create <java.version>17</java.version> property and use it

2024-06-24 07:54 UTC, Elena-Bruyako commented on src/main/java/com/example/controller/BookController.java
> +@RequestMapping(value = "/api/books")
```suggestion
@RequestMapping("/books")
```
Add `server.servlet.context-path=/api` to application.properties

2024-06-24 07:54 UTC, Elena-Bruyako commented on src/main/java/com/example/service/BookServiceImpl.java
>      @Autowired
Remove constructor and use `@RequiredArgsConstructor` instead

2024-06-24 10:47 UTC, sarakhmen requested changes
Some of the previous mentor's comments were not fixed

2024-06-24 10:47 UTC, sarakhmen commented on pom.xml
> +			<version>1.5.5.Final</version>
not fixed

2024-06-25 06:43 UTC, Elena-Bruyako approved these changes
Good job

2024-06-25 06:43 UTC, Elena-Bruyako commented on src/main/java/com/example/controller/BookController.java
> +@RequestMapping(value = "/books")
```suggestion
@RequestMapping("/books")
```

2024-07-17 14:08 UTC, Elena-Bruyako requested changes
see comments
Please, ask your question in chat

2024-07-17 14:08 UTC, Elena-Bruyako commented on src/main/java/com/example/model/Book.java
> +@Where(clause = "is_deleted=false")
Where is deprecated, use SQLRestriction instead

2024-07-17 14:08 UTC, Elena-Bruyako commented on src/main/java/com/example/repository/SpecificationBuilder.java
> +
```suggestion
```

2024-07-17 14:08 UTC, Elena-Bruyako commented on src/main/java/com/example/service/BookServiceImpl.java
> +        bookRepository.updateBookDetails(id, author, title, description);
```suggestion
        Book book = bookRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(.......
        bookMapper.updateBookFromDto(bookDto, book);
        return bookMapper.toDto(bookRepository.save(book));
```

2024-07-17 14:08 UTC, Elena-Bruyako commented on src/main/java/com/example/service/BookServiceImpl.java
> +    public void updateBookDetails(Long id, String author, String title, String description) {
```suggestion
    public void updateBookDetails(Long id, CreateBookRequestDto bookDto) {
```

2024-07-25 18:38 UTC, Elena-Bruyako requested changes
see pr

2024-07-25 18:38 UTC, Elena-Bruyako commented on src/main/java/com/example/dto/UpdateBookDto.java
> +    private String title;
according to the task description Update book request should has more fields

2024-07-25 18:38 UTC, Elena-Bruyako commented on src/main/java/com/example/controller/BookController.java
> +@RequestMapping(value = "/books")
Can't you remove value?

2024-07-25 18:38 UTC, Elena-Bruyako commented on src/main/java/com/example/model/Book.java
> +    private Boolean isDeleted = false;
```suggestion
    private boolean isDeleted = false;
```

2024-07-25 18:38 UTC, Elena-Bruyako commented on src/main/java/com/example/service/BookServiceImpl.java
> +        Book book = bookRepository.findById(id).stream()
Why do you use stream here?

2024-07-25 18:38 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-add-column-is_deleted-in-books.yaml
> +        - addColumn:
auto rollback not supports such changes, so in prod application it won't work 
add is_deleted in exists changelog 01

2024-07-26 07:21 UTC, vladshender commented
thank you for your patience!

2024-07-26 07:27 UTC, Elena-Bruyako requested changes
see comments

2024-07-26 07:27 UTC, Elena-Bruyako commented on src/main/java/com/example/dto/UpdateBookDto.java
> +public class UpdateBookDto {
```suggestion
public class UpdateBookRequestDto {
```

2024-07-26 07:27 UTC, Elena-Bruyako commented on src/main/java/com/example/dto/UpdateBookDto.java
> +    private String title;
Not fixed
Example of request body
```
{
  "title": "Updated Title",
  "author": "Updated Author",
  "isbn": "978-1234567890",
  "price": 19.99,
  "description": "Updated description",
  "coverImage": "https://example.com/updated-cover-image.jpg"
}
```

2024-07-26 07:27 UTC, Elena-Bruyako commented on src/main/java/com/example/service/BookServiceImpl.java
> +        Book book = bookRepository.getReferenceById(id);
https://www.baeldung.com/spring-data-jpa-getreferencebyid-findbyid-methods

In this case you can use findById

2024-07-26 07:27 UTC, Elena-Bruyako commented on src/main/java/com/example/service/BookServiceImpl.java
> +    public void updateBookDetails(Long id, UpdateBookDto updateBookDto) {
```suggestion
    public BookDto updateBookDetails(Long id, UpdateBookDto updateBookDto) {
```

2024-07-26 10:31 UTC, Elena-Bruyako approved these changes
well done

2024-07-26 10:34 UTC, merged