Add global exception handler and validation
vladshender/Online-Book-Store pull request #6
Opened 2024-07-26 10:06 UTC by vladshender

2024-07-26 10:29 UTC, Elena-Bruyako requested changes
There are changes from previous HW with mistakes.

2024-07-26 10:59 UTC, vladshender commented
I do not understand what is the error?

2024-07-30 13:57 UTC, vladshender commented
I created a separate branch, executed the task and made a request to the pool. The code changes are only visible for this task, I think. The problem is the organization of Git? I asked a question about Git in the chat, but I was not answered. Please help, what should I do?

2024-07-31 12:50 UTC, MentorMateAcademy requested changes

2024-07-31 12:50 UTC, MentorMateAcademy commented on src/main/java/com/example/dto/CreateBookRequestDto.java
>      private String author;
maybe better @notblank?

2024-07-31 12:50 UTC, MentorMateAcademy commented on src/main/java/com/example/dto/UpdateBookRequestDto.java
>      private String coverImage;
What difference from CreateBookRequestDto?

2024-07-31 12:50 UTC, MentorMateAcademy commented on src/main/java/com/example/exception/CustomGlobalExceptionHandler.java
> +        body.put("errors", errors);
save strings to constants

2024-08-02 16:49 UTC, merged